[package]
name = "planet-renderer"
version = "0.1.0"
authors = ["Noah Craig <noahcraig123@gmail.com>"]
edition = "2018"

[lib]
crate-type = ['cdylib']

[dependencies]
wasm-bindgen = "0.2.70"
js-sys = "0.3.47"

[dependencies.web-sys]
version = "0.3.47"
features = [
    "WebGlRenderingContext"
]
